// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'22712081906691612d2fa312f3106a903c9d212ef09bea2575cf864decab20e3'>;
export type ExecutionHash =
  ExecutionHashBase<'af63d79fb9f72fe813e47c5957c6ac940ee6c3b2a3b1e70a8132c196a53f0414'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Auditoria: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly usuarioId: CodecTypes['pg/int4@1']['output'] | null;
      readonly documentoId: CodecTypes['pg/int4@1']['output'] | null;
      readonly recurso: CodecTypes['pg/text@1']['output'];
      readonly accion: CodecTypes['pg/text@1']['output'];
      readonly resultado: CodecTypes['pg/text@1']['output'];
      readonly motivo: CodecTypes['pg/text@1']['output'] | null;
      readonly direccionIp: CodecTypes['pg/text@1']['output'] | null;
      readonly ubicacion: CodecTypes['pg/text@1']['output'] | null;
      readonly dispositivo: CodecTypes['pg/text@1']['output'] | null;
      readonly fecha: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly Departamento: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly nombre: CodecTypes['pg/text@1']['output'];
      readonly descripcion: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly Documento: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly titulo: CodecTypes['pg/text@1']['output'];
      readonly descripcion: CodecTypes['pg/text@1']['output'] | null;
      readonly nivelConfidencialidad: CodecTypes['pg/int4@1']['output'];
      readonly estado: CodecTypes['pg/text@1']['output'];
      readonly pais: CodecTypes['pg/text@1']['output'];
      readonly propietarioId: CodecTypes['pg/int4@1']['output'];
      readonly departamentoId: CodecTypes['pg/int4@1']['output'];
      readonly fechaCreacion: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly actualizadoEn: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly Permiso: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly nombre: CodecTypes['pg/text@1']['output'];
      readonly descripcion: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly Politica: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly nombre: CodecTypes['pg/text@1']['output'];
      readonly descripcion: CodecTypes['pg/text@1']['output'];
      readonly tipo: CodecTypes['pg/text@1']['output'];
      readonly activa: CodecTypes['pg/bool@1']['output'];
      readonly creadaEn: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly actualizadaEn: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly Rol: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly nombre: CodecTypes['pg/text@1']['output'];
      readonly descripcion: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly RolPermiso: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly rolId: CodecTypes['pg/int4@1']['output'];
      readonly permisoId: CodecTypes['pg/int4@1']['output'];
    };
    readonly Usuario: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly nombre: CodecTypes['pg/text@1']['output'];
      readonly correo: CodecTypes['pg/text@1']['output'];
      readonly password: CodecTypes['pg/text@1']['output'];
      readonly nivelSeguridad: CodecTypes['pg/int4@1']['output'];
      readonly pais: CodecTypes['pg/text@1']['output'];
      readonly tipoContrato: CodecTypes['pg/text@1']['output'];
      readonly estado: CodecTypes['pg/text@1']['output'];
      readonly rolId: CodecTypes['pg/int4@1']['output'];
      readonly departamentoId: CodecTypes['pg/int4@1']['output'] | null;
      readonly creadoEn: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly actualizadoEn: CodecTypes['pg/timestamptz-string@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Auditoria: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly usuarioId: CodecTypes['pg/int4@1']['input'] | null;
      readonly documentoId: CodecTypes['pg/int4@1']['input'] | null;
      readonly recurso: CodecTypes['pg/text@1']['input'];
      readonly accion: CodecTypes['pg/text@1']['input'];
      readonly resultado: CodecTypes['pg/text@1']['input'];
      readonly motivo: CodecTypes['pg/text@1']['input'] | null;
      readonly direccionIp: CodecTypes['pg/text@1']['input'] | null;
      readonly ubicacion: CodecTypes['pg/text@1']['input'] | null;
      readonly dispositivo: CodecTypes['pg/text@1']['input'] | null;
      readonly fecha: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly Departamento: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly nombre: CodecTypes['pg/text@1']['input'];
      readonly descripcion: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly Documento: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly titulo: CodecTypes['pg/text@1']['input'];
      readonly descripcion: CodecTypes['pg/text@1']['input'] | null;
      readonly nivelConfidencialidad: CodecTypes['pg/int4@1']['input'];
      readonly estado: CodecTypes['pg/text@1']['input'];
      readonly pais: CodecTypes['pg/text@1']['input'];
      readonly propietarioId: CodecTypes['pg/int4@1']['input'];
      readonly departamentoId: CodecTypes['pg/int4@1']['input'];
      readonly fechaCreacion: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly actualizadoEn: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly Permiso: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly nombre: CodecTypes['pg/text@1']['input'];
      readonly descripcion: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly Politica: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly nombre: CodecTypes['pg/text@1']['input'];
      readonly descripcion: CodecTypes['pg/text@1']['input'];
      readonly tipo: CodecTypes['pg/text@1']['input'];
      readonly activa: CodecTypes['pg/bool@1']['input'];
      readonly creadaEn: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly actualizadaEn: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly Rol: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly nombre: CodecTypes['pg/text@1']['input'];
      readonly descripcion: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly RolPermiso: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly rolId: CodecTypes['pg/int4@1']['input'];
      readonly permisoId: CodecTypes['pg/int4@1']['input'];
    };
    readonly Usuario: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly nombre: CodecTypes['pg/text@1']['input'];
      readonly correo: CodecTypes['pg/text@1']['input'];
      readonly password: CodecTypes['pg/text@1']['input'];
      readonly nivelSeguridad: CodecTypes['pg/int4@1']['input'];
      readonly pais: CodecTypes['pg/text@1']['input'];
      readonly tipoContrato: CodecTypes['pg/text@1']['input'];
      readonly estado: CodecTypes['pg/text@1']['input'];
      readonly rolId: CodecTypes['pg/int4@1']['input'];
      readonly departamentoId: CodecTypes['pg/int4@1']['input'] | null;
      readonly creadoEn: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly actualizadoEn: CodecTypes['pg/timestamptz-string@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly auditoria: {
      readonly accion: CodecTypes['pg/text@1']['output'];
      readonly direccionIp: CodecTypes['pg/text@1']['output'] | null;
      readonly dispositivo: CodecTypes['pg/text@1']['output'] | null;
      readonly documentoId: CodecTypes['pg/int4@1']['output'] | null;
      readonly fecha: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly motivo: CodecTypes['pg/text@1']['output'] | null;
      readonly recurso: CodecTypes['pg/text@1']['output'];
      readonly resultado: CodecTypes['pg/text@1']['output'];
      readonly ubicacion: CodecTypes['pg/text@1']['output'] | null;
      readonly usuarioId: CodecTypes['pg/int4@1']['output'] | null;
    };
    readonly departamento: {
      readonly descripcion: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly nombre: CodecTypes['pg/text@1']['output'];
    };
    readonly documento: {
      readonly actualizadoEn: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly departamentoId: CodecTypes['pg/int4@1']['output'];
      readonly descripcion: CodecTypes['pg/text@1']['output'] | null;
      readonly estado: CodecTypes['pg/text@1']['output'];
      readonly fechaCreacion: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly nivelConfidencialidad: CodecTypes['pg/int4@1']['output'];
      readonly pais: CodecTypes['pg/text@1']['output'];
      readonly propietarioId: CodecTypes['pg/int4@1']['output'];
      readonly titulo: CodecTypes['pg/text@1']['output'];
    };
    readonly permiso: {
      readonly descripcion: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly nombre: CodecTypes['pg/text@1']['output'];
    };
    readonly politica: {
      readonly activa: CodecTypes['pg/bool@1']['output'];
      readonly actualizadaEn: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly creadaEn: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly descripcion: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly nombre: CodecTypes['pg/text@1']['output'];
      readonly tipo: CodecTypes['pg/text@1']['output'];
    };
    readonly rol: {
      readonly descripcion: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly nombre: CodecTypes['pg/text@1']['output'];
    };
    readonly rolPermiso: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly permisoId: CodecTypes['pg/int4@1']['output'];
      readonly rolId: CodecTypes['pg/int4@1']['output'];
    };
    readonly usuario: {
      readonly actualizadoEn: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly correo: CodecTypes['pg/text@1']['output'];
      readonly creadoEn: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly departamentoId: CodecTypes['pg/int4@1']['output'] | null;
      readonly estado: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly nivelSeguridad: CodecTypes['pg/int4@1']['output'];
      readonly nombre: CodecTypes['pg/text@1']['output'];
      readonly pais: CodecTypes['pg/text@1']['output'];
      readonly password: CodecTypes['pg/text@1']['output'];
      readonly rolId: CodecTypes['pg/int4@1']['output'];
      readonly tipoContrato: CodecTypes['pg/text@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly auditoria: {
      readonly accion: CodecTypes['pg/text@1']['input'];
      readonly direccionIp: CodecTypes['pg/text@1']['input'] | null;
      readonly dispositivo: CodecTypes['pg/text@1']['input'] | null;
      readonly documentoId: CodecTypes['pg/int4@1']['input'] | null;
      readonly fecha: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly motivo: CodecTypes['pg/text@1']['input'] | null;
      readonly recurso: CodecTypes['pg/text@1']['input'];
      readonly resultado: CodecTypes['pg/text@1']['input'];
      readonly ubicacion: CodecTypes['pg/text@1']['input'] | null;
      readonly usuarioId: CodecTypes['pg/int4@1']['input'] | null;
    };
    readonly departamento: {
      readonly descripcion: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly nombre: CodecTypes['pg/text@1']['input'];
    };
    readonly documento: {
      readonly actualizadoEn: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly departamentoId: CodecTypes['pg/int4@1']['input'];
      readonly descripcion: CodecTypes['pg/text@1']['input'] | null;
      readonly estado: CodecTypes['pg/text@1']['input'];
      readonly fechaCreacion: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly nivelConfidencialidad: CodecTypes['pg/int4@1']['input'];
      readonly pais: CodecTypes['pg/text@1']['input'];
      readonly propietarioId: CodecTypes['pg/int4@1']['input'];
      readonly titulo: CodecTypes['pg/text@1']['input'];
    };
    readonly permiso: {
      readonly descripcion: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly nombre: CodecTypes['pg/text@1']['input'];
    };
    readonly politica: {
      readonly activa: CodecTypes['pg/bool@1']['input'];
      readonly actualizadaEn: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly creadaEn: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly descripcion: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly nombre: CodecTypes['pg/text@1']['input'];
      readonly tipo: CodecTypes['pg/text@1']['input'];
    };
    readonly rol: {
      readonly descripcion: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly nombre: CodecTypes['pg/text@1']['input'];
    };
    readonly rolPermiso: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly permisoId: CodecTypes['pg/int4@1']['input'];
      readonly rolId: CodecTypes['pg/int4@1']['input'];
    };
    readonly usuario: {
      readonly actualizadoEn: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly correo: CodecTypes['pg/text@1']['input'];
      readonly creadoEn: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly departamentoId: CodecTypes['pg/int4@1']['input'] | null;
      readonly estado: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly nivelSeguridad: CodecTypes['pg/int4@1']['input'];
      readonly nombre: CodecTypes['pg/text@1']['input'];
      readonly pais: CodecTypes['pg/text@1']['input'];
      readonly password: CodecTypes['pg/text@1']['input'];
      readonly rolId: CodecTypes['pg/int4@1']['input'];
      readonly tipoContrato: CodecTypes['pg/text@1']['input'];
    };
  };
};

export namespace Models {
  export type public_Usuario = {
    id: CodecTypes['pg/int4@1']['output'];
    nombre: CodecTypes['pg/text@1']['output'];
    correo: CodecTypes['pg/text@1']['output'];
    password: CodecTypes['pg/text@1']['output'];
    nivelSeguridad: CodecTypes['pg/int4@1']['output'];
    pais: CodecTypes['pg/text@1']['output'];
    tipoContrato: CodecTypes['pg/text@1']['output'];
    estado: CodecTypes['pg/text@1']['output'];
    rolId: CodecTypes['pg/int4@1']['output'];
    departamentoId: CodecTypes['pg/int4@1']['output'] | null;
    creadoEn: CodecTypes['pg/timestamptz-string@1']['output'];
    actualizadoEn: CodecTypes['pg/timestamptz-string@1']['output'];
    auditorias: public_Auditoria[];
    departamento: public_Departamento | null;
    documentos: public_Documento[];
    rol: public_Rol;
    readonly [RelationKeys]?: 'auditorias' | 'departamento' | 'documentos' | 'rol';
  };
  export type public_Rol = {
    id: CodecTypes['pg/int4@1']['output'];
    nombre: CodecTypes['pg/text@1']['output'];
    descripcion: CodecTypes['pg/text@1']['output'] | null;
    permisos: public_RolPermiso[];
    usuarios: public_Usuario[];
    readonly [RelationKeys]?: 'permisos' | 'usuarios';
  };
  export type public_Permiso = {
    id: CodecTypes['pg/int4@1']['output'];
    nombre: CodecTypes['pg/text@1']['output'];
    descripcion: CodecTypes['pg/text@1']['output'] | null;
    roles: public_RolPermiso[];
    readonly [RelationKeys]?: 'roles';
  };
  export type public_RolPermiso = {
    id: CodecTypes['pg/int4@1']['output'];
    rolId: CodecTypes['pg/int4@1']['output'];
    permisoId: CodecTypes['pg/int4@1']['output'];
    permiso: public_Permiso;
    rol: public_Rol;
    readonly [RelationKeys]?: 'permiso' | 'rol';
  };
  export type public_Departamento = {
    id: CodecTypes['pg/int4@1']['output'];
    nombre: CodecTypes['pg/text@1']['output'];
    descripcion: CodecTypes['pg/text@1']['output'] | null;
    documentos: public_Documento[];
    usuarios: public_Usuario[];
    readonly [RelationKeys]?: 'documentos' | 'usuarios';
  };
  export type public_Documento = {
    id: CodecTypes['pg/int4@1']['output'];
    titulo: CodecTypes['pg/text@1']['output'];
    descripcion: CodecTypes['pg/text@1']['output'] | null;
    nivelConfidencialidad: CodecTypes['pg/int4@1']['output'];
    estado: CodecTypes['pg/text@1']['output'];
    pais: CodecTypes['pg/text@1']['output'];
    propietarioId: CodecTypes['pg/int4@1']['output'];
    departamentoId: CodecTypes['pg/int4@1']['output'];
    fechaCreacion: CodecTypes['pg/timestamptz-string@1']['output'];
    actualizadoEn: CodecTypes['pg/timestamptz-string@1']['output'];
    auditorias: public_Auditoria[];
    departamento: public_Departamento;
    propietario: public_Usuario;
    readonly [RelationKeys]?: 'auditorias' | 'departamento' | 'propietario';
  };
  export type public_Politica = {
    id: CodecTypes['pg/int4@1']['output'];
    nombre: CodecTypes['pg/text@1']['output'];
    descripcion: CodecTypes['pg/text@1']['output'];
    tipo: CodecTypes['pg/text@1']['output'];
    activa: CodecTypes['pg/bool@1']['output'];
    creadaEn: CodecTypes['pg/timestamptz-string@1']['output'];
    actualizadaEn: CodecTypes['pg/timestamptz-string@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type public_Auditoria = {
    id: CodecTypes['pg/int4@1']['output'];
    usuarioId: CodecTypes['pg/int4@1']['output'] | null;
    documentoId: CodecTypes['pg/int4@1']['output'] | null;
    recurso: CodecTypes['pg/text@1']['output'];
    accion: CodecTypes['pg/text@1']['output'];
    resultado: CodecTypes['pg/text@1']['output'];
    motivo: CodecTypes['pg/text@1']['output'] | null;
    direccionIp: CodecTypes['pg/text@1']['output'] | null;
    ubicacion: CodecTypes['pg/text@1']['output'] | null;
    dispositivo: CodecTypes['pg/text@1']['output'] | null;
    fecha: CodecTypes['pg/timestamptz-string@1']['output'];
    documento: public_Documento | null;
    usuario: public_Usuario | null;
    readonly [RelationKeys]?: 'documento' | 'usuario';
  };
}

export declare const models: {
  public: {
    Usuario: Models.public_Usuario;
    Rol: Models.public_Rol;
    Permiso: Models.public_Permiso;
    RolPermiso: Models.public_RolPermiso;
    Departamento: Models.public_Departamento;
    Documento: Models.public_Documento;
    Politica: Models.public_Politica;
    Auditoria: Models.public_Auditoria;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly auditoria: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly usuarioId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly documentoId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly recurso: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly accion: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly resultado: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly motivo: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly direccionIp: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly ubicacion: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly dispositivo: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly fecha: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'auditoria_usuarioId_idx_5f01c7d6';
                  readonly prefix: 'auditoria_usuarioId_idx';
                  readonly columns: readonly ['usuarioId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'auditoria_documentoId_idx_4a2fed80';
                  readonly prefix: 'auditoria_documentoId_idx';
                  readonly columns: readonly ['documentoId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'auditoria';
                    readonly columns: readonly ['usuarioId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'usuario';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'auditoria';
                    readonly columns: readonly ['documentoId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'documento';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly departamento: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly nombre: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly descripcion: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['nombre'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly documento: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly titulo: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly descripcion: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly nivelConfidencialidad: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 1>;
                  };
                };
                readonly estado: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'PENDIENTE'>;
                  };
                };
                readonly pais: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'PERU'>;
                  };
                };
                readonly propietarioId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly departamentoId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly fechaCreacion: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly actualizadoEn: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'documento_propietarioId_idx_a1de0397';
                  readonly prefix: 'documento_propietarioId_idx';
                  readonly columns: readonly ['propietarioId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'documento_departamentoId_idx_d1d4bda1';
                  readonly prefix: 'documento_departamentoId_idx';
                  readonly columns: readonly ['departamentoId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'documento';
                    readonly columns: readonly ['propietarioId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'usuario';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'documento';
                    readonly columns: readonly ['departamentoId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'departamento';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly permiso: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly nombre: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly descripcion: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['nombre'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly politica: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly nombre: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly descripcion: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly tipo: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly activa: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
                readonly creadaEn: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly actualizadaEn: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['nombre'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly rol: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly nombre: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly descripcion: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['nombre'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly rolPermiso: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly rolId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly permisoId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['rolId', 'permisoId'] }];
              indexes: readonly [
                {
                  readonly name: 'rolPermiso_rolId_idx_6774d828';
                  readonly prefix: 'rolPermiso_rolId_idx';
                  readonly columns: readonly ['rolId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'rolPermiso_permisoId_idx_fac66949';
                  readonly prefix: 'rolPermiso_permisoId_idx';
                  readonly columns: readonly ['permisoId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'rolPermiso';
                    readonly columns: readonly ['rolId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'rol';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'rolPermiso';
                    readonly columns: readonly ['permisoId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'permiso';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly usuario: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly nombre: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly correo: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly password: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly nivelSeguridad: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 1>;
                  };
                };
                readonly pais: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'PERU'>;
                  };
                };
                readonly tipoContrato: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'INTERNO'>;
                  };
                };
                readonly estado: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'ACTIVO'>;
                  };
                };
                readonly rolId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly departamentoId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly creadoEn: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly actualizadoEn: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['correo'] }];
              indexes: readonly [
                {
                  readonly name: 'usuario_rolId_idx_6774d828';
                  readonly prefix: 'usuario_rolId_idx';
                  readonly columns: readonly ['rolId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'usuario_departamentoId_idx_d1d4bda1';
                  readonly prefix: 'usuario_departamentoId_idx';
                  readonly columns: readonly ['departamentoId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'usuario';
                    readonly columns: readonly ['rolId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'rol';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'usuario';
                    readonly columns: readonly ['departamentoId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'departamento';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly usuario: { readonly namespace: 'public' & NamespaceId; readonly model: 'Usuario' };
    readonly rol: { readonly namespace: 'public' & NamespaceId; readonly model: 'Rol' };
    readonly permiso: { readonly namespace: 'public' & NamespaceId; readonly model: 'Permiso' };
    readonly rolPermiso: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'RolPermiso';
    };
    readonly departamento: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Departamento';
    };
    readonly documento: { readonly namespace: 'public' & NamespaceId; readonly model: 'Documento' };
    readonly politica: { readonly namespace: 'public' & NamespaceId; readonly model: 'Politica' };
    readonly auditoria: { readonly namespace: 'public' & NamespaceId; readonly model: 'Auditoria' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Auditoria: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly usuarioId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly documentoId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly recurso: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly accion: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly resultado: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly motivo: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly direccionIp: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly ubicacion: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly dispositivo: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly fecha: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly documento: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Documento';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['documentoId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly usuario: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Usuario';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['usuarioId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'auditoria';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly usuarioId: { readonly column: 'usuarioId' };
                readonly documentoId: { readonly column: 'documentoId' };
                readonly recurso: { readonly column: 'recurso' };
                readonly accion: { readonly column: 'accion' };
                readonly resultado: { readonly column: 'resultado' };
                readonly motivo: { readonly column: 'motivo' };
                readonly direccionIp: { readonly column: 'direccionIp' };
                readonly ubicacion: { readonly column: 'ubicacion' };
                readonly dispositivo: { readonly column: 'dispositivo' };
                readonly fecha: { readonly column: 'fecha' };
              };
            };
          };
          readonly Departamento: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly nombre: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly descripcion: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly documentos: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Documento';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['departamentoId'];
                };
              };
              readonly usuarios: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Usuario';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['departamentoId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'departamento';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly nombre: { readonly column: 'nombre' };
                readonly descripcion: { readonly column: 'descripcion' };
              };
            };
          };
          readonly Documento: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly titulo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly descripcion: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly nivelConfidencialidad: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly estado: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly pais: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly propietarioId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly departamentoId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly fechaCreacion: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly actualizadoEn: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly auditorias: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Auditoria';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['documentoId'];
                };
              };
              readonly departamento: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Departamento';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['departamentoId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly propietario: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Usuario';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['propietarioId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'documento';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly titulo: { readonly column: 'titulo' };
                readonly descripcion: { readonly column: 'descripcion' };
                readonly nivelConfidencialidad: { readonly column: 'nivelConfidencialidad' };
                readonly estado: { readonly column: 'estado' };
                readonly pais: { readonly column: 'pais' };
                readonly propietarioId: { readonly column: 'propietarioId' };
                readonly departamentoId: { readonly column: 'departamentoId' };
                readonly fechaCreacion: { readonly column: 'fechaCreacion' };
                readonly actualizadoEn: { readonly column: 'actualizadoEn' };
              };
            };
          };
          readonly Permiso: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly nombre: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly descripcion: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly roles: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'RolPermiso';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['permisoId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'permiso';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly nombre: { readonly column: 'nombre' };
                readonly descripcion: { readonly column: 'descripcion' };
              };
            };
          };
          readonly Politica: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly nombre: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly descripcion: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly tipo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly activa: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly creadaEn: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly actualizadaEn: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'politica';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly nombre: { readonly column: 'nombre' };
                readonly descripcion: { readonly column: 'descripcion' };
                readonly tipo: { readonly column: 'tipo' };
                readonly activa: { readonly column: 'activa' };
                readonly creadaEn: { readonly column: 'creadaEn' };
                readonly actualizadaEn: { readonly column: 'actualizadaEn' };
              };
            };
          };
          readonly Rol: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly nombre: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly descripcion: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly permisos: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'RolPermiso';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['rolId'];
                };
              };
              readonly usuarios: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Usuario';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['rolId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'rol';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly nombre: { readonly column: 'nombre' };
                readonly descripcion: { readonly column: 'descripcion' };
              };
            };
          };
          readonly RolPermiso: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly rolId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly permisoId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly permiso: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Permiso';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['permisoId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly rol: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Rol' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['rolId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'rolPermiso';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly rolId: { readonly column: 'rolId' };
                readonly permisoId: { readonly column: 'permisoId' };
              };
            };
          };
          readonly Usuario: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly nombre: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly correo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly password: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly nivelSeguridad: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly pais: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly tipoContrato: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly estado: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly rolId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly departamentoId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly creadoEn: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly actualizadoEn: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly auditorias: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Auditoria';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['usuarioId'];
                };
              };
              readonly departamento: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Departamento';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['departamentoId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly documentos: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Documento';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['propietarioId'];
                };
              };
              readonly rol: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Rol' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['rolId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'usuario';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly nombre: { readonly column: 'nombre' };
                readonly correo: { readonly column: 'correo' };
                readonly password: { readonly column: 'password' };
                readonly nivelSeguridad: { readonly column: 'nivelSeguridad' };
                readonly pais: { readonly column: 'pais' };
                readonly tipoContrato: { readonly column: 'tipoContrato' };
                readonly estado: { readonly column: 'estado' };
                readonly rolId: { readonly column: 'rolId' };
                readonly departamentoId: { readonly column: 'departamentoId' };
                readonly creadoEn: { readonly column: 'creadoEn' };
                readonly actualizadoEn: { readonly column: 'actualizadoEn' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'documento';
            readonly column: 'actualizadoEn';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'politica';
            readonly column: 'actualizadaEn';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'usuario';
            readonly column: 'actualizadoEn';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
